BethanysPieShop/BethanysPieShop/Controllers/FeedbackController.cs
using BethanysPieShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        private readonly IFeedbackRepository feedbackRepository;

        public FeedbackController( IFeedbackRepository feedbackRepositoryParam )
        {
            feedbackRepository = feedbackRepositoryParam;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index( Feedback feedback )
        {
            if ( ModelState.IsValid )
            {
                feedbackRepository.AddFeedback( feedback );
                return RedirectToAction( "FeedbackComplete" );
            }
            else
            {
                return View( feedback );
            }
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

BethanysPieShop/BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Bethany's Pie Shop</a>
                    </li>
                    <li>
                        <a asp-controller="Feedback" asp-action="Index">Feedback</a>
                    </li>
                </ul>

                @if ( SignInManager.IsSignedIn( User ) )
                {
                    <form asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="javascript:document.getElementById('logoutForm').submit()">Logout
                                </a>
                            </li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li>
                            <a asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    </ul>

                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>
</body>
</html>